# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('owner', models.EmailField(max_length=254)),
                ('contact', models.TextField()),
                ('image', models.ImageField(upload_to='organizer_images')),
                ('links', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='images',
            field=models.ImageField(upload_to='event_images'),
        ),
    ]
