# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowdb', '0002_auto_20170406_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowdb.Category')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowdb.EventDetail')),
            ],
        ),
    ]
